[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
build_flags =
    -Wl,-u,vfprintf -lprintf_flt
    -Wl,-u,vfscanf  -lscanf_flt
    -lm
build_unflags = -fno-strict-aliasing
lib_extra_dirs = lib/MCAL, lib/ECAL, lib/SRV
lib_deps =
    feilipu/FreeRTOS@^11.1.0-3
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    markruys/DHT@^1.0.0
